---
- name: Add junior user Igor
  user:
    name: Igor
    password: "{{ junior_password }}"
    update_password: on_create
    group: "{{ junior_devops_group }}"
    shell: /bin/bash

- name: Add admin user BetterIgor
  user:
    name: BetterIgor
    password: "{{ admin_password }}"
    update_password: on_create
    group: "{{ admin_devops_group }}"
    shell: /bin/bash
    system: yes